#!/bin/bash
# B. Yin

# nohup  ~/yin_github/linux_config/mktar2  -gz  aaa/  &  



if [ $# != 2 ]; then
    echo "==> Wrong input. Abort!"
    exit

else
    dirn=$2
    dirn=${dirn%/}

    logfile=$dirn.tar.log
    
    date > $logfile
    echo -e "==> compressing $dirn\n" >> $logfile
    
    case "$1" in
        -xz)
            tar -cJf  $dirn.tar.xz  $dirn  >>  $logfile
            rtrn_code=$?
            ;;
        -gz)
            tar -czf  $dirn.tar.gz  $dirn  >>  $logfile
            rtrn_code=$?
            ;;
        -tar)
            tar -cf   $dirn.tar     $dirn  >>  $logfile
            rtrn_code=$?            
            ;;
         *)
            echo "Wrong flag. ABORT!"
            exit
            ;;
    esac
fi



if [ $rtrn_code == 0 ]; then
    echo -e "\n==> done!" >> $logfile
    date                  >> $logfile
else
    echo 'return code:' $rtrn_code
    echo -e "\n==> tar fails. Abort!" >> $logfile
    exit
fi




