#!/bin/bash
# B. Yin

# nohup  ~/yin_github/linux_config/mktar2  -xz  aaa/  &  



if [ $# != 2 ]; then
    echo "==> Wrong input. Abort!"
    exit

else
    dirn=$2
    dirn=${dirn%/}

    logfile=$dirn.tar.log
    
    date > $logfile
    echo -e "==> compressing $dirn\n" >> $logfile
    
    case "$1" in
        -xz)
            tar -cJf  $dirn.tar.xz  $dirn  >>  $logfile  2>&1
            rtrn_code=$?
            ;;
        -gz)
            tar -czf  $dirn.tar.gz  $dirn  >>  $logfile  2>&1
            rtrn_code=$?
            ;;
        -tar)
            tar -cf   $dirn.tar     $dirn  >>  $logfile  2>&1
            rtrn_code=$?            
            ;;
         *)
            echo "Wrong flag. ABORT!"
            exit
            ;;
    esac
fi



date >> $logfile
echo "return code of tar:" $rtrn_code >> $logfile 

if [ $rtrn_code == 0 ]; then
    echo -e "\n==> done!" >> $logfile
    date                  >> $logfile

    echo -e "\n\n\n$ ls -alsh $dirn " >> $logfile
    ls -alsh $dirn                    >> $logfile
    echo    " "                       >> $logfile 

else
    echo -e "\n==> tar fails. Abort!" >> $logfile
    exit
fi




